import os

os.chdir(os.path.dirname(os.path.realpath(__file__)))

lang=input("請輸入這個新語言包的名稱：")
file=input("請輸入要學習的圖檔名稱：")
os.system(f"cp {file} {lang}.src")
os.system(f"tesseract {lang}.src {lang} batch.nochop makebox")
input(f"請先確認{lang}.box檔案內容是否正確在按Enter鍵")
os.system(f"tesseract {lang}.src {lang} nobatch box.train")
os.system(f"unicharset_extractor {lang}.box")
os.system(f"echo {lang} 0 0 0 0 0 > font_properties")
os.system(f"shapeclustering -F font_properties -U unicharset {lang}.tr")
os.system(f"mftraining -F font_properties -U unicharset -O unicharset {lang}.tr")
os.system(f"cntraining {lang}.tr")
os.system(f"mv unicharset {lang}.unicharset")
os.system(f"mv normproto {lang}.normproto")
os.system(f"mv pffmtable {lang}.pffmtable")
os.system(f"mv shapetable {lang}.shapetable")
os.system(f"mv inttemp {lang}.inttemp")
os.system(f"unlink {lang}.src")
os.system(f"unlink {lang}.box")
os.system(f"unlink {lang}.tr")
os.system(f"unlink font_properties")
os.system(f"combine_tessdata {lang}.")
os.system(f"unlink {lang}.unicharset")
os.system(f"unlink {lang}.normproto")
os.system(f"unlink {lang}.pffmtable")
os.system(f"unlink {lang}.shapetable")
os.system(f"unlink {lang}.inttemp")
os.system(f"mv {lang}.traineddata /usr/share/tesseract-ocr/4.00/tessdata/{lang}.traineddata")